import pandas as pd 
import csv
import re

class sigpid():
	def __init__(self):
		self.listNew = ['com.android.voicemail.permission.ADD_VOICEMAIL',
		'android.permission.USE_SIP',
		'android.permission.BIND_DEVICE_ADMIN',
		'android.permission.READ_SYNC_SETTINGS',
		'android.permission.READ_CALENDAR',
		'android.permission.CHANGE_CONFIGURATION',
		'android.permission.GET_PACKAGE_SIZE',
		'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS',
		'android.permission.CLEAR_APP_CACHE',
		'android.permission.BIND_INPUT_METHOD',
		'android.permission.BIND_REMOTEVIEWS',
		'android.permission.BATTERY_STATS',
		'android.permission.AUTHENTICATE_ACCOUNTS',
		'android.permission.RESTART_PACKAGES',
		'android.permission.INTERNET',
		'android.permission.RECORD_AUDIO',
		'android.permission.ACCESS_MOCK_LOCATION',
		'android.permission.WRITE_PROFILE',
		'android.permission.READ_SOCIAL_STREAM',
		'android.permission.VIBRATE',
		'android.permission.WRITE_CALL_LOG',
		'android.permission.FLASHLIGHT',
		'android.permission.GLOBAL_SEARCH',
		'android.permission.CHANGE_WIFI_STATE',
		'android.permission.BROADCAST_STICKY',
		'android.permission.KILL_BACKGROUND_PROCESSES',
		'android.permission.SET_TIME_ZONE',
		'android.permission.BLUETOOTH_ADMIN',
		'android.permission.CAMERA',
		'android.permission.SET_WALLPAPER',
		'android.permission.WAKE_LOCK',
		'android.permission.MANAGE_ACCOUNTS',
		'android.permission.WRITE_CALENDAR',
		'android.permission.SET_PREFERRED_APPLICATIONS',
		'android.permission.NFC',
		'android.permission.CALL_PHONE',
		'android.permission.DISABLE_KEYGUARD',
		'android.permission.BIND_VPN_SERVICE',
		'com.android.browser.permission.READ_HISTORY_BOOKMARKS',
		'android.permission.READ_SMS',
		'android.permission.REORDER_TASKS',
		'android.permission.MODIFY_AUDIO_SETTINGS',
		'android.permission.READ_PHONE_STATE',
		'android.permission.ADD_SYSTEM_SERVICE',
		'android.permission.WRITE_SETTINGS',
		'android.permission.BIND_WALLPAPER',
		'android.permission.WRITE_SOCIAL_STREAM',
		'android.permission.USE_CREDENTIALS',
		'android.permission.SEND_SMS',
		'android.permission.WRITE_USER_DICTIONARY',
		'android.permission.WRITE_OWNER_DATA',
		'android.permission.ACCESS_COARSE_LOCATION',
		'android.permission.SET_PROCESS_FOREGROUND',
		'android.permission.READ_EXTERNAL_STORAGE',
		'android.permission.SYSTEM_ALERT_WINDOW',
		'android.permission.CHANGE_WIFI_MULTICAST_STATE',
		'android.permission.RECEIVE_BOOT_COMPLETED',
		'com.android.alarm.permission.SET_ALARM',
		'android.permission.WRITE_CONTACTS',
		'android.permission.PROCESS_OUTGOING_CALLS',
		'android.permission.EXPAND_STATUS_BAR',
		'android.permission.READ_OWNER_DATA',
		'android.permission.RECEIVE_MMS',
		'android.permission.GET_TASKS',
		'android.permission.READ_CALL_LOG',
		'android.permission.READ_SYNC_STATS',
		'android.permission.BIND_TEXT_SERVICE',
		'android.permission.RECEIVE_WAP_PUSH',
		'android.permission.SUBSCRIBED_FEEDS_WRITE',
		'android.permission.ACCESS_WIFI_STATE',
		'android.permission.ACCESS_FINE_LOCATION',
		'android.permission.SUBSCRIBED_FEEDS_READ',
		'android.permission.ACCESS_NETWORK_STATE',
		'android.permission.FOTA_UPDATE',
		'android.permission.WRITE_SMS',
		'android.permission.PERSISTENT_ACTIVITY',
		'com.android.browser.permission.WRITE_HISTORY_BOOKMARKS',
		'android.permission.CHANGE_NETWORK_STATE',
		'android.permission.WRITE_SYNC_SETTINGS',
		'android.permission.BIND_ACCESSIBILITY_SERVICE',
		'android.permission.GET_ACCOUNTS',
		'android.permission.READ_PROFILE',
		'android.permission.RECEIVE_SMS',
		'android.permission.WRITE_EXTERNAL_STORAGE',
		'android.permission.BLUETOOTH',
		'android.permission.SET_WALLPAPER_HINTS',
		'android.permission.READ_CONTACTS',
		'android.permission.READ_USER_DICTIONARY',
		'class']
		self.listOld = ['ADD_VOICEMAIL',
		'USE_SIP',
		'BIND_DEVICE_ADMIN',
		'READ_SYNC_SETTINGS',
		'READ_CALENDAR',
		'CHANGE_CONFIGURATION',
		'GET_PACKAGE_SIZE',
		'ACCESS_LOCATION_EXTRA_COMMANDS',
		'CLEAR_APP_CACHE',
		'BIND_INPUT_METHOD',
		'BIND_REMOTEVIEWS',
		'BATTERY_STATS',
		'AUTHENTICATE_ACCOUNTS',
		'RESTART_PACKAGES',
		'INTERNET',
		'RECORD_AUDIO',
		'ACCESS_MOCK_LOCATION',
		'WRITE_PROFILE',
		'READ_SOCIAL_STREAM',
		'VIBRATE',
		'WRITE_CALL_LOG',
		'FLASHLIGHT',
		'GLOBAL_SEARCH',
		'CHANGE_WIFI_STATE',
		'BROADCAST_STICKY',
		'KILL_BACKGROUND_PROCESSES',
		'SET_TIME_ZONE',
		'BLUETOOTH_ADMIN',
		'CAMERA',
		'SET_WALLPAPER',
		'WAKE_LOCK',
		'MANAGE_ACCOUNTS',
		'WRITE_CALENDAR',
		'SET_PREFERRED_APPLICATIONS',
		'NFC',
		'CALL_PHONE',
		'DISABLE_KEYGUARD',
		'BIND_VPN_SERVICE',
		'READ_HISTORY_BOOKMARKS',
		'READ_SMS',
		'REORDER_TASKS',
		'MODIFY_AUDIO_SETTINGS',
		'READ_PHONE_STATE',
		'ADD_SYSTEM_SERVICE',
		'WRITE_SETTINGS',
		'BIND_WALLPAPER',
		'WRITE_SOCIAL_STREAM',
		'USE_CREDENTIALS',
		'SEND_SMS',
		'WRITE_USER_DICTIONARY',
		'WRITE_OWNER_DATA',
		'ACCESS_COARSE_LOCATION',
		'SET_PROCESS_FOREGROUND',
		'READ_EXTERNAL_STORAGE',
		'SYSTEM_ALERT_WINDOW',
		'CHANGE_WIFI_MULTICAST_STATE',
		'RECEIVE_BOOT_COMPLETED',
		'SET_ALARM',
		'WRITE_CONTACTS',
		'PROCESS_OUTGOING_CALLS',
		'EXPAND_STATUS_BAR',
		'READ_OWNER_DATA',
		'RECEIVE_MMS',
		'GET_TASKS',
		'READ_CALL_LOG',
		'READ_SYNC_STATS',
		'BIND_TEXT_SERVICE',
		'RECEIVE_WAP_PUSH',
		'SUBSCRIBED_FEEDS_WRITE',
		'ACCESS_WIFI_STATE',
		'ACCESS_FINE_LOCATION',
		'SUBSCRIBED_FEEDS_READ',
		'ACCESS_NETWORK_STATE',
		'FOTA_UPDATE',
		'WRITE_SMS',
		'PERSISTENT_ACTIVITY',
		'WRITE_HISTORY_BOOKMARKS',
		'CHANGE_NETWORK_STATE',
		'WRITE_SYNC_SETTINGS',
		'BIND_ACCESSIBILITY_SERVICE',
		'GET_ACCOUNTS',
		'READ_PROFILE',
		'RECEIVE_SMS',
		'WRITE_EXTERNAL_STORAGE',
		'BLUETOOTH',
		'SET_WALLPAPER_HINTS',
		'READ_CONTACTS',
		'READ_USER_DICTIONARY',
		'class']
	def replace(self, dirin, dirout):
		f1 = open(dirin, "r")
		f2 = open(dirout, "w")
		for line in f1:
			for one in range(0, 89):
				if self.listOld[one] in line:
					line = line.replace(self.listOld[one], self.listNew[one])
			f2.write(line)
		f1.close()
		f2.close()
	def toTest(self, dirin, dirout):
		permission = pd.read_csv(dirin)
		listPer = permission[self.listNew]
		listPer.to_csv(dirout, index = False)
if __name__=="__main__":
	ad = sigpid()
	#ad.replace('F:\\document\\88permissionBycckenny\\drebinSource.csv', 'F:\\document\\88permissionBycckenny\\drebinFormat.csv')
	ad.toTest('F:\\document\\88permissionBycckenny\\drebinFormat.csv', 'F:\\document\\88permissionBycckenny\\drebin88.csv')